/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ManagementSystem;

import ConnectionProvider.ConnectionProvider;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author SRINIVASAN N R
 */
public class SuggestionReport extends javax.swing.JFrame {

    /**
     * Creates new form SuggestionReport
     */
    public SuggestionReport() {
        initComponents();
    }
    public SuggestionReport(String rollNo) {
        initComponents();
        jTextField1.setText(rollNo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 560));
        setMinimumSize(new java.awt.Dimension(700, 560));
        setPreferredSize(new java.awt.Dimension(700, 560));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("               Suggestion Report");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 410, 50));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 120, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 110, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel2.setText("Roll No");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 510, 230));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 60, -1));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 110, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManagementSystem/schoolPic2.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO
        String rollNo=jTextField1.getText();
        try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            ResultSet rs=st.executeQuery("SELECT * FROM  student INNER JOIN RESULT WHERE STUDENT.rollNo='"+rollNo+"' AND result.rollNO='"+rollNo+"'");
            if(!rs.first()){
                JOptionPane.showMessageDialog(null,"RollNo doesn't exist");
            }
            else{
                jTextField2.setText(rs.getString(1));
                
                //m1 -physics
                //m2 =maths
                //m3 -chemistry
                //m4- eletrical
                //m5-biology
                int m1=Integer.parseInt(rs.getString(8));
                int m2=Integer.parseInt(rs.getString(9));
                int m3=Integer.parseInt(rs.getString(10));
                int m4=Integer.parseInt(rs.getString(11));
                int m5=Integer.parseInt(rs.getString(12));
                
                
                String welcome="Hi"+rs.getString(1);
                
                String phy="";
                if(m1>80){
                    phy+="Your score is excellent in Physics,\n";
                }
                else if(m1>70){
                    phy+="YOur score is good in Physics,\n";
                }
                else if(m1>50){
                    phy+="Your Score is less study concentration required in Physics,\n";
                }
                else{
                    phy+="Your Score is BAD in Physics you must improve.\n";
                }
                
                if(m2>80){
                    phy+="Your score is excellent in Maths,\n";
                }
                else if(m2>70){
                    phy+="YOur score is good in Maths,\n";
                }
                else if(m2>50){
                    phy+="Your Score is less study concentration required in Maths,\n";
                }
                else{
                    phy+="Your Score is BAD in Maths you must improve.\n";
                }
                
                if(m3>80){
                    phy+="Your score is excellent in Chemistry,\n";
                }
                else if(m3>70){
                    phy+="YOur score is good in Chemistry,\n";
                }
                else if(m3>50){
                    phy+="Your Score is less study concentration required in Chemistry,\n";
                }
                else{
                    phy+="Your Score is BAD in Chemistry you must improve.\n";
                }
                
                if(m4>80){
                    phy+="Your score is excellent in Electrical,\n";
                }
                else if(m4>70){
                    phy+="YOur score is good in Electrical,\n";
                }
                else if(m4>50){
                    phy+="Your Score is less study concentration required in Electrical,\n";
                }
                else{
                    phy+="Your Score is BAD in Electrical you must improve.\n";
                }
                
                if(m5>80){
                    phy+="Your score is excellent in Biology,\n";
                }
                else if(m5>70){
                    phy+="YOur score is good in Biology,\n";
                }
                else if(m5>50){
                    phy+="Your Score is less study concentration required in Biology,\n";
                }
                else{
                    phy+="Your Score is BAD in Biology you must improve.\n";
                }
                
                
                
                
                jTextArea1.setText(phy);
                
                if(m1<30 || m2<30 || m3<30 || m4<30 || m5<30){
                    //jTextField13.setText("Fail");
                }
                else{
                   // jTextField13.setText("Pass");
                }
                
                jTextField1.setEditable(false);
                jTextField2.setEditable(false);
     
                

            }
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuggestionReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuggestionReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuggestionReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuggestionReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuggestionReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
